version: '3.8'

services:
  couchbase:
    image: couchbase/server:7.6.1
    container_name: couchbase
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "11210:11210"
    environment:
      - COUCHBASE_ADMIN_USERNAME=erdi
      - COUCHBASE_ADMIN_PASSWORD=erdi123
    volumes:
      - couchbase-data:/opt/couchbase/var
    #healthcheck:
    #  test: ["CMD", "curl", "-f", "http://localhost:8091/pools"]
      #  interval: 30s
      # retries: 3
      #start_period: 30s
      # timeout: 10s

  app:
    image: todolist-be:latest
    container_name: todolist-be
    depends_on:
      - couchbase
    environment:
      - COUCHBASE_CONNECTION_STRING=couchbase://couchbase
      - COUCHBASE_USERNAME=erdi
      - COUCHBASE_PASSWORD=erdi123
      - COUCHBASE_BUCKET_PRIMARY=todolist-docker
      - COUCHBASE_BUCKET_USER=todolist-app
    ports:
      - "9292:9292"

volumes:
  couchbase-data:
